---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "microblog-backend"
  namespace: "default"
  labels:
    app: "microblog-backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "microblog-backend"
  template:
    metadata:
      labels:
        app: "microblog-backend"
    spec:
      containers:
      - name: "microblog-backend-sha256"
        image: "gcr.io/el-practicekubernetescluster/microblog-backend@sha256:1f6298be5f660390994fc5ce0492da477c7bc6011c6ce776f7dde60d6c20ea08"
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: postgres
                key: db
          - name: DB_HOST
            value: postgresdb-service
          - name: DB_PORT
            value: "5432"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "microblog-backend-service"
  namespace: "default"
  labels:
    app: "microblog-backend"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: "microblog-backend"
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-backend
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: backend.el-test.donley.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: microblog-backend-service
          servicePort: 80
