---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "microblog-frontend"
  labels:
    app: "microblog-frontend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "microblog-frontend"
  template:
    metadata:
      labels:
        app: "microblog-frontend"
    spec:
      containers:
      - name: "microblog-frontend-sha256"
        image: "gcr.io/el-practicekubernetescluster/microblog-frontend@sha256:130a499fb8835d5215e108263642a4a2eb3be3914e9c7b8f4b45a6e2d47bb05d"
        env:
          - name: VUE_APP_BASE_API_URL
            value: microblog-backend-service
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "microblog-frontend-service"
  #namespace: "default"
  labels:
    app: "microblog-frontend"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  selector:
    app: "microblog-frontend"
  type: "ClusterIP"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-frontend
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: frontend.el-test.donley.cloud
    http:
      paths:
      - path: /
        backend:
          serviceName: microblog-frontend-service
          servicePort: 80
