---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "postgresdb"
  labels:
    app: "postgresdb"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "postgresdb"
  template:
    metadata:
      labels:
        app: "postgresdb"
    spec:
      containers:
      - name: "postgresdb"
        image: "postgres:12.1-alpine"
        volumeMounts:
          - mountPath: "/var/lib/postgresql"
            name: postgresdb-data
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres
                key: db
      volumes:
      - name: postgresdb-data
        persistentVolumeClaim:
          claimName: postgresdb-data
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "postgresdb-service"
  namespace: "default"
  labels:
    app: "postgresdb"
spec:
  ports:
  - protocol: "TCP"
    port: 5432
    targetPort: 5432
  selector:
    app: "postgresdb"
  type: "ClusterIP"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresdb-data
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  username: YWRtaW4=
  password: cGFzc3dvcmQ=
  db: ZGF0YWJhc2U=